plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("com.github.johnrengelman.shadow")
    application
}

group = "${rootProject.group}"
version = "${rootProject.version}"
val artifactName by extra { "${rootProject.name.toLowerCase()}-${project.name.toLowerCase()}" }
val theMainClass by extra { "com.hoffi.mpp.cli.AppKt" }

kotlin {
    jvmToolchain {
        val javaVersion: JavaLanguageVersion by rootProject.extra
        (this as JavaToolchainSpec).languageVersion.set(javaVersion)
        //vendor.set(JvmVendorSpec.ADOPTOPENJDK)
    }
    jvm {
        testRuns["test"].executionTask.configure {
            useJUnit()
        }
    }
    val hostOS: String by rootProject.extra
    when (hostOS) {
        "MAC" -> macosX64() {
            binaries {
                executable {
                    // entry point function = package with non-inside-object main method + ".main" (= name of the main function)
                    entryPoint(theMainClass.replaceAfterLast(".", "main"))
                }
            }
        }
        "LINUX" -> linuxX64() {
            binaries {
                executable {
                    // entry point function = package with non-inside-object main method + ".main" (= name of the main function)
                    entryPoint(theMainClass.replaceAfterLast(".", "main"))
                }
            }
        }
        "WINDOWS" -> mingwX64() {
            binaries {
                executable {
                    // entry point function = package with non-inside-object main method + ".main" (= name of the main function)
                    entryPoint(theMainClass.replaceAfterLast(".", "main"))
                }
            }
        }
        else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
    }
    sourceSets {
        val commonMain by getting  { // predefined by gradle multiplatform plugin
            dependencies {
                implementation(project(":lib"))
                implementation("io.github.microutils:kotlin-logging:${Deps.Logging.KotlinLogging.version}")
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:${Deps.Misc.KotlinxDatetime.version}")
                //api(platform("com.squareup.okio:okio-bom:3.0.0"))
                implementation("com.squareup.okio:okio:${Deps.Squareup.Okio.version}")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:${Deps.Serialization.KotlinxJson.version}")
                //implementation("com.charleskorn.kaml:kaml:${Deps.Misc.KOTLINXYAML.VERSION}")
                implementation("net.mamoe.yamlkt:yamlkt:${Deps.Serialization.KotlinxYaml.version}")

                implementation("com.github.ajalt.clikt:clikt:${Deps.Misc.Clikt.version}")
            }
        }
        val commonTest by getting {
            dependencies {
            }
        }

        val jvmMain by getting {
            //print("${name} dependsOn: ")
            //println(dependsOn.map { it.name }.joinToString())
            dependencies {
                runtimeOnly("ch.qos.logback:logback-classic") { version { strictly(Deps.Logging.Logback.version) } }
                //implementation("org.slf4j:slf4j-api:1.7.30")
            }
        }
        val jvmTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
        when (hostOS) {
            "MAC" -> {
                val macosX64Main by getting {
                    dependencies {
                    }}}
            "LINUX" -> {
                val linuxX64Main by getting {
                    dependencies {
                    }}}
            "WINDOWS" -> {
                val mingwX64Main by getting {
                    dependencies {
                    }}}
            else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
        }
    }
}

application {
    mainClass.set(theMainClass)
}

tasks.getByName<JavaExec>("run") {
    classpath(tasks.getByName<Jar>("jvmJar")) // so that the JS artifacts generated by `jvmJar` can be found and served
}

tasks {
    val shadowCreate by creating(com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar::class) {
        manifest {
            attributes["Main-Class"] = theMainClass
        }
        mergeServiceFiles()

        //archiveClassifier.set("fat")
        from(kotlin.jvm().compilations.getByName("main").output)
        configurations =
            mutableListOf(kotlin.jvm().compilations.getByName("main").compileDependencyFiles)
    }
    val build by existing {
        dependsOn(shadowCreate)
    }
}

// ################################################################################################
// #####    pure informational stuff on stdout    #################################################
// ################################################################################################
tasks.register("printClasspath") {
    group = "misc"
    description = "print classpath"
    doLast {
        //project.getConfigurations().filter { it.isCanBeResolved }.forEach {
        //    println(it.name)
        //}
        //println()
        val targets = listOf(
            "metadataCommonMainCompileClasspath",
            "commonMainApiDependenciesMetadata",
            "commonMainImplementationDependenciesMetadata",
            "jvmCompileClasspath",
            "kotlinCompilerClasspath"
        )
        targets.forEach { targetConfiguration ->
            println("$targetConfiguration:")
            println("=".repeat("$targetConfiguration:".length))
            project.getConfigurations()
                .getByName(targetConfiguration).files
                // filters only existing and non-empty dirs
                .filter { (it.isDirectory() && it.listFiles().isNotEmpty()) || it.isFile() }
                .forEach { println(it) }
        }
    }
}
